[package]
name = "sqlite-img"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-loadable = "0.0.5"
image = {version="0.24.4", features=["webp-encoder"]}

[lib]
crate-type=["lib", "staticlib", "cdylib"]